// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web; // استخدام إعدادات الويب للينكس
      case TargetPlatform.fuchsia: // إضافة الحالة الناقصة
        throw UnsupportedError('Fuchsia is not supported.');
      // لاحظ أننا حذفنا الـ default أو جعلناه يرمي خطأ
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAazMj-_vstlN7iyltTKCA2v9MZsqWTSA',
    appId: '1:156617951416:web:5e8e6901299a7e19730c4d',
    messagingSenderId: '156617951416',
    projectId: 'flow-chat-5e38b',
    authDomain: 'flow-chat-5e38b.firebaseapp.com',
    databaseURL:
        'https://flow-chat-5e38b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flow-chat-5e38b.firebasestorage.app',
    measurementId: 'G-JBYCZH9TLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFHC_omy98SN_vpRvoRD4j2xCjV8-RUG8',
    appId: '1:156617951416:android:daaf63f01e1d695f730c4d',
    messagingSenderId: '156617951416',
    projectId: 'flow-chat-5e38b',
    databaseURL:
        'https://flow-chat-5e38b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flow-chat-5e38b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZmnCrLMM-G2elxTTPh3Fz2nkyR-BakU',
    appId: '1:156617951416:ios:fc80bc7237809e67730c4d',
    messagingSenderId: '156617951416',
    projectId: 'flow-chat-5e38b',
    databaseURL:
        'https://flow-chat-5e38b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flow-chat-5e38b.firebasestorage.app',
    iosClientId:
        '156617951416-qfcghqopdiqhad9lel18mo9q4o71kdkc.apps.googleusercontent.com',
    iosBundleId: 'com.izutec.flow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZmnCrLMM-G2elxTTPh3Fz2nkyR-BakU',
    appId: '1:156617951416:ios:fc80bc7237809e67730c4d',
    messagingSenderId: '156617951416',
    projectId: 'flow-chat-5e38b',
    databaseURL:
        'https://flow-chat-5e38b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flow-chat-5e38b.firebasestorage.app',
    iosClientId:
        '156617951416-qfcghqopdiqhad9lel18mo9q4o71kdkc.apps.googleusercontent.com',
    iosBundleId: 'com.izutec.flow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAazMj-_vstlN7iyltTKCA2v9MZsqWTSA',
    appId: '1:156617951416:web:bdee67f20639425c730c4d',
    messagingSenderId: '156617951416',
    projectId: 'flow-chat-5e38b',
    authDomain: 'flow-chat-5e38b.firebaseapp.com',
    databaseURL:
        'https://flow-chat-5e38b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flow-chat-5e38b.firebasestorage.app',
    measurementId: 'G-JBD504HJHN',
  );
}
